server:
  port: 8079
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/**/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bysj?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    autoconfigure:
      #跳过security自动配置
      exclude:
        - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
        - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
sa-token:
  # token名称（同时也是cookie名称）
  token-name: satoken
  # token有效期，单位s 默认30天，-1代表永不过期
  timeout: 2592000
  # token零时有效期
  activity-timeout: 600000
  # 是否允许同一账号并发登录(为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时候，是否共享一个token(为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

flowable:
  check-process-definitions: true
  # 关闭定时任务JOB
  async-executor-activate: false
  # 将databaseSchemaUpdate设置为true。当flowable发现数据库不一致的时候，会自动将数据库表结构更新到最新版本。
  database-schema-update: false

alipay:
  appId: 2021000122678234
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC9WCieSnGfUa9WfslvnrMMB+jZ2DH5T1FgaD9FmTHq+3Kr3VAcsUlXTBJ5TJ5PyUR4lCY2GO0/+X6ICHo1o5Kqx6xVlI/cV/ttvfeu96i+hcw0a/QnJEmB7TbdpeXbedDeyhavI5oo3RjCaIADmig51C506S453/whsxseQb8vaBvgsgDkoLIP4usSH+gMZgbqEjw1nyZdOT9QziV2YizgluRIxHKeVU5TTwCV7kWS7IsIUVWplBeAtb6TtdMspm3rFwx33nK/HfUkM3yjGxWjmyGj5MFKKXzJA+Imln4S8FH1BmFSabHbN9FG6zQJ3Ao19ICWbx1J2dJX0abLOSFDAgMBAAECggEAdOq/Ch9F0e8KqgpYMEh6nu8zZXEOSrgjs7grebqDDGqAAIgEM/N1KiabMbOR/gp18U7p2XXC6kIRU8aIUB7VLgdl7uJxgsoBQ16OVsgutpa/5Y7TkGfjzArCWlNagA/UXf3DzBnb02fTJhiJE7BZLnxKw35JQQuCEP0bva8zcv1xsO6U/hOPzctQ2P4P1wd/erdD9ThoxcJNQPU3pUmJMfoeBnXUyDaHNLi8rI9NAc0pNmBPsnDz+b/76ULeTCIn3XdMUqt4iP5krb6nnhy8dzAtmastemNzw5vRibfmBwVsnBw28C3Zo25WuVS6dDdz1SKqpzuOWPnAm+t34MaooQKBgQDtPTzWJVpEfQfYNtk0rxkLdXVzW6t4lEWFNa/g54fNreV5D269HfmuFPR+GyE7j8MfQyDoi87SJ26mf2YbHj0TsSsLPGL2/xoAT/aZrHl27NEkxfGixq3Bhd2Bh8LKN7fjwhsB9fTvQhpnV279I02dFMsOaSn/HWknpVLJ/QFZvwKBgQDMUVHBLMl9lR0GOlmY8LNLp68Jf/f+Q1pkLaz6bUrh/0eff43c/OiFoOmrqpMvM8HIQlU0fnPtwTOGCtr+oqOgn80FfwuRr4Yo7dMIFFX+2Bw4eK2qTthhg+FKV92ZF3KBXp028sGsMi24ogIMYk5OR8KJRG82sJOgdsCg9c1xfQKBgF10pzeQ5VtfiaySBsSrSYlrDwaPkR/iAPT17kAB1Uyf+WrUOoKDgW0jUiEvXMsS2gHBtwAEu0esQvmR7E44fkT4oQU/F5lHax2+Yl2tRPglWEpNM+A0thQrQNQbABAbHPS67Vq7Ym6yMqaNGerccmGz5D3cDbAzDM6SYOezJEoPAoGAVZPyBFF4C6u7PnKOOKsIzjVr8TSycMNRRwiCnVnNtZ8xJrNMfjVIR0BA33BQucKZ9gEioxwb/oefxxMg6urAUnTccOLnu5ujO91xOL8bzeRC3bxeMSlZJG8SnAr1fDv/8APrIarISBG0aNMivIEof007RDdvxZ5sFxfmUwThihkCgYAvNV2rcQTS6mXiq4K4gAR+9FCOE4T7xpcipznBQokpMTNoksvEFPYGlRtKd5lEZmALcfi/t2amWstikcPod5y1scboziCpiZ2I8uCAxfEQ8X5u+qpJPEd+9RH445umJ1J3oafSCm+3xVuzVVT7PJK69HXTD65k8cwA/qlmqxqZlA==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAigwqfx+P+RU7WMTBPDAj0WVbiF0rgSEsOzwd/PRIll3Ve09mvswXzd9SMzvW/rf9+FTBdt2jvyvcHR3uUfaYhluJh9MQ0QtiYigszfPi+p8WXr23uCzj0jZCxVXgRcGHOG3Leh3ac+q+b22qwqyW6IarR2w2alUpdOTZjHmDyin6Cn6qugRJoolqFpoGTxOvsdFOg9skt0z03Y9MCASZZ6YPuEE9ndz+xwZJKR8P58kCKZD0J3Q6tdBmolF732YUk3r526wqa9EIm0TqqfHr9FlYlfDJDie+jWJOmX2Brgdr/wpGCGAVaFX8pqr9k1ZZeUK+jfn39Pe/GGr723NrawIDAQAB
  notifyUrl: http://5iypyy.natappfree.cc/alipay/notify
