server:
  port: 8062
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/**/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bysj?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    autoconfigure:
      #跳过security自动配置
      exclude:
        - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
        - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
sa-token:
  # token名称（同时也是cookie名称）
  token-name: satoken
  # token有效期，单位s 默认30天，-1代表永不过期
  timeout: 2592000
  # token零时有效期
  activity-timeout: 600000
  # 是否允许同一账号并发登录(为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时候，是否共享一个token(为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

flowable:
  check-process-definitions: true
  # 关闭定时任务JOB
  async-executor-activate: false
  # 将databaseSchemaUpdate设置为true。当flowable发现数据库不一致的时候，会自动将数据库表结构更新到最新版本。
  database-schema-update: true

